from typing import Dict

# ── App data directory aliases ────────────────────────────────────────────────
# Maps lowercased folder names to bundle ID prefixes.
# Prevents false positives for apps using non-standard dir names.

APP_DIR_ALIASES: Dict[str, str] = {
    # ── Microsoft ─────────────────────────────────────────────────────────
    "code":                             "com.microsoft.vscode",
    "code - insiders":                  "com.microsoft.vscode-insiders",
    "microsoft edge":                   "com.microsoft.edgemac",
    "microsoft autoupdate":             "com.microsoft.autoupdate2",
    "onedrive":                         "com.microsoft.onedrive",
    "microsoft onenote":                "com.microsoft.onenote.mac",
    "microsoft outlook":                "com.microsoft.outlook",
    "microsoft word":                   "com.microsoft.word",
    "microsoft excel":                  "com.microsoft.excel",
    "microsoft powerpoint":             "com.microsoft.powerpoint",
    "microsoft teams":                  "com.microsoft.teams",
    "microsoft teams (work or school)": "com.microsoft.teams2",
    "microsoft teams classic":          "com.microsoft.teams",
    "excel":                            "com.microsoft.excel",
    "word":                             "com.microsoft.word",
    "powerpoint":                       "com.microsoft.powerpoint",
    "outlook":                          "com.microsoft.outlook",
    "onenote":                          "com.microsoft.onenote.mac",
    "teams":                            "com.microsoft.teams",
    "copilot":                          "com.microsoft.copilot",
    "visual studio":                    "com.microsoft.visual-studio",
    "visual studio code":               "com.microsoft.vscode",
    "skype":                            "com.skype.skype",
    "remote desktop":                   "com.microsoft.rdc.macos",

    # ── Google ────────────────────────────────────────────────────────────
    "google":                           "com.google",
    "chrome":                           "com.google.chrome",
    "google chrome":                    "com.google.chrome",
    "google chrome canary":             "com.google.chrome.canary",
    "google drive":                     "com.google.drivefs",
    "google earth pro":                 "com.google.googleearthpro",
    "googledrive":                      "com.google.drivefs",

    # ── JetBrains ─────────────────────────────────────────────────────────
    "jetbrains":                        "com.jetbrains",
    "intellij idea":                    "com.jetbrains.intellij",
    "intellij idea ce":                 "com.jetbrains.intellij.ce",
    "pycharm":                          "com.jetbrains.pycharm",
    "pycharm ce":                       "com.jetbrains.pycharm.ce",
    "webstorm":                         "com.jetbrains.webstorm",
    "goland":                           "com.jetbrains.goland",
    "clion":                            "com.jetbrains.clion",
    "datagrip":                         "com.jetbrains.datagrip",
    "rider":                            "com.jetbrains.rider",
    "rubymine":                         "com.jetbrains.rubymine",
    "phpstorm":                         "com.jetbrains.phpstorm",
    "appcode":                          "com.jetbrains.appcode",
    "fleet":                            "com.jetbrains.fleet",
    "jetbrains toolbox":                "com.jetbrains.toolbox",
    "jetbrains toolbox app":            "com.jetbrains.toolbox",
    "rustrover":                        "com.jetbrains.rustrover",
    "aquaa":                            "com.jetbrains.aqua",
    
    # ── Browsers ──────────────────────────────────────────────────────────
    "firefox":                          "org.mozilla.firefox",
    "mozilla firefox":                  "org.mozilla.firefox",
    "firefox nightly":                  "org.mozilla.nightly",
    "chromium":                         "org.chromium.chromium",
    "brave browser":                    "com.brave.browser",
    "brave browser beta":               "com.brave.browser.beta",
    "bravesoftware":                    "com.brave.browser",  # Fix for config deletion
    "opera":                            "com.operasoftware.opera",
    "opera gx":                         "com.operasoftware.operagx",
    "vivaldi":                          "com.vivaldi.vivaldi",
    "arc":                              "company.thebrowser.browser",
    "orion":                            "com.nickvision.orion",
    "tor browser":                      "org.torproject.torbrowser",
    "waterfox":                         "net.nickolaj.nickelodeon",
    "sidekick":                         "com.nicklodeon.nickelodeon",
    "brave":                            "com.brave.browser",
    "edge":                             "com.microsoft.edgemac",
    "sigmaos":                          "com.sigmaos.sigmaos.macos",
    "duckduckgo":                       "com.duckduckgo.macos.browser",
    "mullvad browser":                  "net.mullvad.mullvadbrowser",
    
    # ── AI Tools ──────────────────────────────────────────────────────────
    "chatgpt":                          "com.openai.chat",
    "claude":                            "com.anthropic.claudefordesktop",
    "windsurf":                          "com.exafunction.windsurf",
    "cursor":                            "com.todesktop.230313mzl4w4u92",
    "ollama":                            "com.electron.ollama",
    "lm studio":                         "com.lmstudio.lmstudio",
    "jan":                               "jan.ai",
    "gpt4all":                           "com.nomic.gpt4all",

    # ── Communication ─────────────────────────────────────────────────────
    "slack":                            "com.tinyspeck.slackmacgap",
    "discord":                          "com.hnc.discord",
    "telegram":                         "ru.keepcoder.telegram",
    "telegram desktop":                 "ru.keepcoder.telegram",
    "whatsapp":                         "net.whatsapp.whatsapp",
    "signal":                           "org.whispersystems.signal-desktop",
    "zoom":                             "us.zoom.xos",
    "zoom.us":                          "us.zoom.xos",
    "zulip":                            "org.zulip.zulip",
    "mattermost":                       "com.mattermost.desktop",
    "element":                          "io.element.desktop",
    "thunderbird":                      "org.mozilla.thunderbird",
    "spark":                            "com.readdle.smartemail.macos",
    "webex":                            "com.cisco.webexmeetingsapp",
    "wechat":                           "com.tencent.xinWeChat",
    "line":                              "jp.naver.line.mac",
    "viber":                             "com.viber.osx",

    # ── Productivity ──────────────────────────────────────────────────────
    "notion":                           "notion.id",
    "notion enhanced":                  "notion.id",
    "notion calendar":                   "com.cron.electron",
    "obsidian":                         "md.obsidian",
    "logseq":                           "com.electron.logseq",
    "bear":                             "net.shinyfrog.bear",
    "craft":                            "io.craft.desktop",
    "1password 7":                      "com.agilebits.onepassword7",
    "1password":                        "com.1password.1password",
    "lastpass":                         "com.lastpass.lastpassmacdesktop",
    "bitwarden":                        "com.bitwarden.desktop",
    "alfred":                           "com.runningwithcrayons.alfred",
    "raycast":                          "com.raycast.macos",
    "todoist":                          "com.todoist.macos",
    "things":                           "com.culturedcode.thingsmac",
    "things 3":                         "com.culturedcode.thingsmac",
    "fantastical":                      "com.flexibits.fantastical2.mac",
    "fantastical 2":                    "com.flexibits.fantastical2.mac",
    "cardhop":                          "com.flexibits.cardhop.mac",
    "day one":                          "com.bloombuilt.dayone-mac",
    "drafts":                           "com.agiletortoise.drafts",
    "grammarly":                        "com.grammarly.projectllama",
    "grammarly desktop":                "com.grammarly.projectllama",
    "evernote":                         "com.evernote.evernote",
    "typora":                           "abnerworks.typora",
    "ulysses":                          "com.soulmen.ulysses",
    "ia writer":                        "pro.writer.mac",
    "devonthink 3":                     "com.devon-technologies.think3",
    "devonthink":                       "com.devon-technologies.think3",
    "linear":                           "com.linear.linear",
    "superhuman":                       "com.superhuman.desktop",
    "ticktick":                          "com.TickTick.task.mac",
    "dashlane":                          "com.dashlane.Dashlane",
    "keeper":                            "com.keepersecurity.passwordmanager",

    # ── Design ────────────────────────────────────────────────────────────
    "figma":                            "com.figma.desktop",
    "figma beta":                       "com.figma.Desktop.beta",
    "sketch":                           "com.bohemiancoding.sketch3",
    "zeplin":                           "io.zeplin.zeplin",
    "invision":                         "com.invisionapp.studio",
    "pixelmator pro":                   "com.pixelmatorteam.pixelmator.x",
    "affinity photo":                   "com.seriflabs.affinityphoto",
    "affinity photo 2":                 "com.seriflabs.affinityphoto2",
    "affinity designer":                "com.seriflabs.affinitydesigner",
    "affinity designer 2":              "com.seriflabs.affinitydesigner2",
    "affinity publisher":               "com.seriflabs.affinitypublisher",
    "affinity publisher 2":             "com.seriflabs.affinitypublisher2",
    "inkscape":                         "org.inkscape.inkscape",
    "gimp":                             "org.gimp.gimp-2.10",
    "canva":                            "com.canva.canva",
    "principle":                        "com.principleformac.principle",
    "pixelmator":                       "com.pixelmatorteam.pixelmator",
    "adobe creative cloud":             "com.adobe.acc.AdobeCreativeCloud",
    "photoshop":                        "com.adobe.photoshop",
    "illustrator":                      "com.adobe.illustrator",
    "lightroom":                        "com.adobe.lightroom",
    "premiere pro":                     "com.adobe.premiere",
    "after effects":                    "com.adobe.aftereffects",
    "blender":                          "org.blenderfoundation.blender",
    "spline":                            "design.spline.Spline",
    "rive":                              "app.rive.editor",

    # ── Dev tools ─────────────────────────────────────────────────────────
    "iterm2":                           "com.googlecode.iterm2",
    "iterm":                            "com.googlecode.iterm2",
    "warp":                             "dev.warp.warp-stable",
    "ghostty":                          "com.mitchellh.ghostty",
    "wezterm":                          "com.github.wez.wezterm",
    "zed":                               "dev.zed.zed",
    "nova":                             "com.panic.nova",
    "bbedit":                           "com.barebones.bbedit",
    "transmit 5":                       "com.panic.transmit",
    "transmit":                         "com.panic.transmit",
    "cyberduck":                        "ch.sudo.cyberduck",
    "tableplus":                        "com.tinyapp.tableplus",
    "sequel pro":                       "com.sequelpro.sequelpro",
    "sequel ace":                       "com.sequel-ace.sequel-ace",
    "db browser for sqlite":            "net.sourceforge.sqlitebrowser",
    "mongodb compass":                  "com.mongodb.compass",
    "beekeeper studio":                 "io.beekeeperstudio.desktop",
    "dbeaver":                          "org.jkiss.dbeaver.core.product",
    "proxyman":                         "com.proxyman.nsproxy",
    "charles":                          "com.xk72.charles",
    "paw":                              "com.luckymarmot.paw",
    "rapidapi":                         "com.luckymarmot.paw",
    "httpie":                           "io.httpie.app",
    "postman":                          "com.postmanlabs.mac",
    "insomnia":                         "com.insomnia.app",
    "sublime text":                     "com.sublimetext.4",
    "sublime merge":                    "com.sublimemerge",
    "atom":                             "com.github.atom",
    "xcodes":                           "com.robotsandpencils.xcodes",
    "dash":                             "com.kapeli.dashmacextras",
    "kaleidoscope":                     "com.blackpixel.kaleidoscope",
    "coderunner":                       "com.krill.coderunner",
    "coteditor":                        "com.coteditor.coteditor",
    "textedit":                         "com.apple.textedit",
    "simulator":                        "com.apple.iphonesimulator",
    "xcode":                            "com.apple.dt.xcode",
    "textmate":                         "com.macromates.textmate",
    "android studio":                   "com.google.android.studio",
    "postico":                           "at.obdev.postico",
    "gitfox":                            "com.bytie.gitfox",
    "dash 5":                            "com.kapeli.dashmacextras",

    # ── Source Control ────────────────────────────────────────────────────
    "tower":                            "com.fournova.tower3",
    "sourcetree":                       "com.torusknot.sourcetreenotmas",
    "fork":                             "com.danlec.fork",
    "gitkraken":                        "com.axosoft.gitkraken",
    "github desktop":                   "com.github.ghd",
    "git-annex":                        "com.manton.gitannex",

    # ── Storage / Cloud ───────────────────────────────────────────────────
    "dropbox":                          "com.getdropbox.dropbox",
    "boxsync":                          "com.box.desktop",
    "box":                              "com.box.desktop",
    "arq":                              "com.haystacksoftware.arq",
    "backblaze":                        "com.backblaze.backblaze",
    "syncthing":                        "com.syncthing.syncthing",
    "resilio sync":                     "com.resilio.sync",
    "tresorit":                         "com.tresorit.mac",
    "mountain duck":                    "io.mountainduck",
    "expandrive":                       "com.expandrive.expandrive3",
    "pcloud":                            "com.pcloud.pcloud.macos",

    # ── Media ─────────────────────────────────────────────────────────────
    "spotify":                          "com.spotify.client",
    "vlc":                              "org.videolan.vlc",
    "iina":                             "com.colliderli.iina",
    "handbrake":                        "fr.handbrake.handbrake",
    "permute 3":                        "com.charliemonroe.permute",
    "permute":                          "com.charliemonroe.permute",
    "downie":                           "com.charliemonroe.downie",
    "downie 4":                         "com.charliemonroe.downie-4",
    "bezel":                            "com.wearereasonablepeople.bezel",
    "davinci resolve":                  "com.blackmagic-design.davinciresolve",
    "obs":                              "com.obsproject.obs-studio",
    "obs studio":                       "com.obsproject.obs-studio",
    "audacity":                         "org.audacityteam.audacity",
    "screenflow":                       "net.telestream.screenflow9",
    "screenflow 10":                    "net.telestream.screenflow10",
    "mpv":                              "io.mpv.player",
    "plex":                             "com.plexapp.plexmediaserver",
    "infuse":                           "com.firecore.infuse",
    "kap":                               "com.wulkano.kap",
    "shottr":                            "cc.ffitch.shottr",
    "cleanshot x":                       "pl.maketheweb.cleanshotx",
    "fina cut pro":                      "com.apple.FinalCut",

    # ── System utilities ──────────────────────────────────────────────────
    "bartender 4":                      "com.surteesstudios.bartender",
    "bartender":                        "com.surteesstudios.bartender",
    "bartender 5":                      "com.surteesstudios.bartender5",
    "magnet":                           "com.crowdcafe.windowmagnet",
    "rectangle":                        "com.knollsoft.rectangle",
    "rectangle pro":                    "com.knollsoft.rectanglepro",
    "macs fan control":                 "crystalidea.macs-fan-control",
    "istatmenus":                       "com.bjango.istatmenus",
    "istat menus":                      "com.bjango.istatmenus",
    "cleanmymac x":                     "com.macpaw.cleanmymac4",
    "cleanmymac":                       "com.macpaw.cleanmymac4",
    "hazel":                            "com.noodlesoft.hazel",
    "keyboard maestro":                 "com.stairways.keyboardmaestro",
    "bettertouchtool":                  "com.hegenberg.bettertouchtool",
    "karabiner-elements":               "org.pqrs.karabiner-elements",
    "karabiner":                        "org.pqrs.karabiner-elements",
    "popclip":                          "com.pilotmoon.popclip",
    "audio hijack":                     "com.rogueamoeba.audiohijack3",
    "loopback":                         "com.rogueamoeba.loopback2",
    "soundsource":                      "com.rogueamoeba.soundsource",
    "appcleaner":                       "com.freemacsoft.appcleaner",
    "the unarchiver":                   "com.macpaw.site.theunarchiver",
    "keka":                             "com.aone.keka",
    "coconutbattery":                   "com.coconut-flavour.coconutbattery3",
    "aldente":                          "com.apphousekitchen.aldente-pro",
    "amphetamine":                      "com.if.amphetamine",
    "lungo":                            "com.sindresorhus.lungo",
    "stats":                            "eu.exelban.stats",
    "monitorcontrol":                   "me.guillaumeb.monitorcontrol",
    "hiddenbar":                        "com.dwarvesv.minimalbar",
    "dozer":                            "com.mortennn.dozer",
    "yabai":                            "com.koekeishiya.yabai",
    "skhd":                             "com.koekeishiya.skhd",
    "alt-tab":                          "com.lwouis.alt-tab-macos",
    "hammerspoon":                      "org.hammerspoon.hammerspoon",
    "setapp":                           "com.macpaw.setapp",
    "macupdater":                       "com.corecode.macupdater",
    "sparkle":                          "org.sparkle-project.sparkle",
    "daisydisk":                         "com.daisydiskapp.DaisyDiskStandAlone",
    "grandperspective":                   "net.sourceforge.grandperspectiv",

    # ── Virtualisation ────────────────────────────────────────────────────
    "virtualbox":                       "org.virtualbox.app.virtualbox",
    "parallels":                        "com.parallels.desktop.console",
    "parallels desktop":                "com.parallels.desktop.console",
    "vmware fusion":                    "com.vmware.fusion",
    "docker":                           "com.docker.docker",
    "docker desktop":                   "com.docker.docker",
    "utm":                              "com.utmapp.utm",
    "multipass":                        "com.canonical.multipass",
    "orbstack":                          "dev.orbstack.orbstack",

    # ── Gaming ────────────────────────────────────────────────────────────
    "steam":                            "com.valvesoftware.steam",
    "gog galaxy":                       "com.gogcom.galaxyclient",
    "epic games":                       "com.epicgames.launcher",
    "epic games launcher":              "com.epicgames.launcher",
    "battle.net":                       "com.blizzard.bnetlauncher",
    "origin":                            "com.ea.origin",
    "ea app":                            "com.ea.app",
    
    # ── Research / Reference ──────────────────────────────────────────────
    "zotero":                           "org.zotero.zotero",
    "endnote":                          "com.adeptscience.endnotex",
    "calibre":                          "net.kovidgoyal.calibre",
    "mendeley":                          "com.mendeley.desktop",

    # ── Misc ──────────────────────────────────────────────────────────────
    "transmission":                     "org.m0k.transmission",
    "stremio":                          "com.stremio.stremio",
    "youtube music":                    "com.github.th-ch.youtube-music",
    "qbittorrent":                       "org.qbittorrent.qBittorrent",
}
